export const LOADING = 'LOADING'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const ERROR = 'ERROR'
export const CHANGE_EMAIL = 'CHANGE_EMAIL'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const AUTH_END = 'AUTH_END'
export const ERROR_END = 'ERROR_END'

export const HOTELS_LOADED = 'DATA_LOADED'
export const HOTELS_LOADING = 'DATA_LOADING'
export const HOTELS_ERROR = 'DATA_ERROR'
export const SORT_PRICE_ASC = 'SORT_PRICE_ASC'

export const OPTION_TRUE = 'OPTION_TRUE'
export const OPTION_FALSE = 'OPTION_FALSE'

export const HOTELS_DETAIL_LOADING = 'HOTELS_DETAIL_LOADING'
export const HOTELS_DETAIL_LOADED = 'HOTELS_DETAIL_LOADED'
export const HOTELS_DETAIL_ERROR = 'HOTELS_DETAIL_ERROR'

export const ROOM_DETAIL_LOADING = 'ROOM_DETAIL_LOADING'
export const ROOM_DETAIL_LOADED = 'ROOM_DETAIL_LOADED'
export const ROOM_DETAIL_ERROR = 'ROOM_DETAIL_ERROR'

export const MOST_VISITED_ERROR = 'MOST_VISITED_ERROR'
export const MOST_VISITED_LOADED = 'MOST_VISITED_LOADED'
export const MOST_VISITED_LOADING = 'MOST_VISITED_LOADING'

export const CHANGE_DATE_FILTER_HOTEL ='CHANGE_DATE_FILTER_HOTEL'
export const CHANGE_DATE_END_FILTER_HOTEL ='CHANGE_DATE_END_FILTER_HOTEL'

export const POPULAR_LOCATION_LOADING = 'POPULAR_LOCATION_LOADING'
export const POPULAR_LOCATION_LOADED = 'POPULAR_LOCATION_LOADED'
export const POPULAR_LOCATION_ERROR = 'POPULAR_LOCATION_ERROR'

export const TRANSACTION_LOADING = 'TRANSACTION_LOADING'
export const TRANSACTION_LOADED = 'TRANSACTION_LOADED'
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR'

export const TRX_LOADING = 'TRX_LOADING'
export const TRX_ERROR = 'TRX_ERROR'
export const TRX_LOADED = 'TRX_LOADED'

export const TRX_FAILED_LOADING = 'TRX_FAILED_LOADING'
export const TRX_FAILED_LOADED = 'TRX_FAILED_LOADED'
export const TRX_FAILED_ERROR = 'TRX_FAILED_ERROR'

export const BOOK_LOADING = 'BOOK_LOADING'
export const BOOK_LOADED = 'BOOK_LOADED'
export const BOOK_ERROR = 'BOOK_ERROR'
export const BOOK_CLEAR = 'BOOK_CLEAR'



